### PR TITLE
Added basic client for Rate My Professor

### PR DESCRIPTION
**Pull request by ThundR67**
I have created a basic client

### CODE REVIEW

**Comment by ThundR67** [comment]
Also, There is no way to directly search for a classe's rating based on teacher name and class code. First, teacher's id need to be searched from their name. Then, teacher's rating will be pulled. Then, the specific ratings on that class code will be used. However, we can cache teacher's name to their ID in a local database to increase speeds.

**Comment by RobertConde** [comment]
I reformatted what you send over. Make sure it's still fine. I'm still reviewing the code.

**Comment by RobertConde** [comment]
Also, did you put your personal auth token?

**Comment by RobertConde** [comment]
I really like the API however I think we're going to make the browser do the heavy lifting when it comes to data retrieval (i.e. getting the RMP ratings). Here is something I found... https://www.npmjs.com/package/@mtucourses/rate-my-professors

**Comment by ThundR67** [comment]
I actually did base my project from the link you sent

**Comment by RobertConde** [comment]
Going to merge so that we have this as an option. :)

**Pull request merged**
